version: '3.8'

services:
  mysql-db:
    image: mysql:8.0.34
    command: --default-authentication-plugin=caching_sha2_password 
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appointments
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "bash", "-c", "mysqladmin ping -h localhost"]
      interval: 10s
      retries: 5
      timeout: 5s
    volumes:
      - mysql-data:/var/lib/mysql

  dotnet-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "443:443"
    depends_on:
        mysql-db:
          condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # - ASPNETCORE_URLS=https://+:443;http://+:80

volumes:
  mysql-data:
    driver: local